services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 10s   
      timeout: 5s     
      retries: 5      
      start_period: 10s
  indexer:
    build:
      context: .
      dockerfile: ./apps/indexer/Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      indexer:
        condition: service_started
    ports:
      - "3000:3000"
volumes:
  postgres_data: